// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { FoldersControllerCreateData, FoldersControllerCreateResponses, FoldersControllerGetAllData, FoldersControllerGetAllResponses, FoldersControllerGetByIdData, FoldersControllerGetByIdResponses, FoldersControllerRemoveData, FoldersControllerRemoveResponses, PiecesControllerCreateData, PiecesControllerCreateResponses, PiecesControllerGetAllData, PiecesControllerGetAllResponses, PiecesControllerRemoveData, PiecesControllerRemoveResponses, SeedControllerSeedData, SeedControllerSeedResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get all (parent) folders
 */
export const foldersControllerGetAll = <ThrowOnError extends boolean = false>(options?: Options<FoldersControllerGetAllData, ThrowOnError>) => {
    return (options?.client ?? client).get<FoldersControllerGetAllResponses, unknown, ThrowOnError>({
        url: '/folders',
        ...options
    });
};

/**
 * Create a folder
 */
export const foldersControllerCreate = <ThrowOnError extends boolean = false>(options: Options<FoldersControllerCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<FoldersControllerCreateResponses, unknown, ThrowOnError>({
        url: '/folders',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a folder
 */
export const foldersControllerRemove = <ThrowOnError extends boolean = false>(options: Options<FoldersControllerRemoveData, ThrowOnError>) => {
    return (options.client ?? client).delete<FoldersControllerRemoveResponses, unknown, ThrowOnError>({
        url: '/folders/{id}',
        ...options
    });
};

/**
 * Get folder by ID
 */
export const foldersControllerGetById = <ThrowOnError extends boolean = false>(options: Options<FoldersControllerGetByIdData, ThrowOnError>) => {
    return (options.client ?? client).get<FoldersControllerGetByIdResponses, unknown, ThrowOnError>({
        url: '/folders/{id}',
        ...options
    });
};

/**
 * Get all pieces
 */
export const piecesControllerGetAll = <ThrowOnError extends boolean = false>(options?: Options<PiecesControllerGetAllData, ThrowOnError>) => {
    return (options?.client ?? client).get<PiecesControllerGetAllResponses, unknown, ThrowOnError>({
        url: '/pieces',
        ...options
    });
};

/**
 * Create a piece
 */
export const piecesControllerCreate = <ThrowOnError extends boolean = false>(options: Options<PiecesControllerCreateData, ThrowOnError>) => {
    return (options.client ?? client).post<PiecesControllerCreateResponses, unknown, ThrowOnError>({
        url: '/pieces',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a piece
 */
export const piecesControllerRemove = <ThrowOnError extends boolean = false>(options: Options<PiecesControllerRemoveData, ThrowOnError>) => {
    return (options.client ?? client).delete<PiecesControllerRemoveResponses, unknown, ThrowOnError>({
        url: '/pieces/{id}',
        ...options
    });
};

/**
 * Seed the DB.
 */
export const seedControllerSeed = <ThrowOnError extends boolean = false>(options?: Options<SeedControllerSeedData, ThrowOnError>) => {
    return (options?.client ?? client).post<SeedControllerSeedResponses, unknown, ThrowOnError>({
        url: '/seed',
        ...options
    });
};
