// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { CoursesControllerCreateOneLessonByCourseIdV1Data, CoursesControllerCreateOneLessonByCourseIdV1Responses, CoursesControllerCreateOneV1Data, CoursesControllerCreateOneV1Responses, CoursesControllerFindAllV1Data, CoursesControllerFindAllV1Responses, CoursesControllerFindOneByIdWithLessonsV1Data, CoursesControllerFindOneByIdWithLessonsV1Responses, CoursesControllerRemoveOneByIdV1Data, CoursesControllerRemoveOneByIdV1Responses, CoursesControllerUpdateOneByIdV1Data, CoursesControllerUpdateOneByIdV1Responses, CurriculumStepsControllerFindAllWithLessonsV1Data, CurriculumStepsControllerFindAllWithLessonsV1Responses, LessonsControllerOkV1Data, LessonsControllerOkV1Responses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Get courses
 */
export const coursesControllerFindAllV1 = <ThrowOnError extends boolean = false>(options?: Options<CoursesControllerFindAllV1Data, ThrowOnError>) => {
    return (options?.client ?? client).get<CoursesControllerFindAllV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/courses',
        ...options
    });
};

/**
 * Create a course
 */
export const coursesControllerCreateOneV1 = <ThrowOnError extends boolean = false>(options: Options<CoursesControllerCreateOneV1Data, ThrowOnError>) => {
    return (options.client ?? client).post<CoursesControllerCreateOneV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/courses',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Delete a course
 */
export const coursesControllerRemoveOneByIdV1 = <ThrowOnError extends boolean = false>(options: Options<CoursesControllerRemoveOneByIdV1Data, ThrowOnError>) => {
    return (options.client ?? client).delete<CoursesControllerRemoveOneByIdV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/courses/{id}',
        ...options
    });
};

/**
 * Get a course (w/ lessons)
 */
export const coursesControllerFindOneByIdWithLessonsV1 = <ThrowOnError extends boolean = false>(options: Options<CoursesControllerFindOneByIdWithLessonsV1Data, ThrowOnError>) => {
    return (options.client ?? client).get<CoursesControllerFindOneByIdWithLessonsV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/courses/{id}',
        ...options
    });
};

/**
 * Update a course
 */
export const coursesControllerUpdateOneByIdV1 = <ThrowOnError extends boolean = false>(options: Options<CoursesControllerUpdateOneByIdV1Data, ThrowOnError>) => {
    return (options.client ?? client).patch<CoursesControllerUpdateOneByIdV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/courses/{id}',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Create lesson by course ID
 */
export const coursesControllerCreateOneLessonByCourseIdV1 = <ThrowOnError extends boolean = false>(options: Options<CoursesControllerCreateOneLessonByCourseIdV1Data, ThrowOnError>) => {
    return (options.client ?? client).post<CoursesControllerCreateOneLessonByCourseIdV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/courses/{id}/lesson',
        ...options,
        headers: {
            'Content-Type': 'application/json',
            ...options.headers
        }
    });
};

/**
 * Lessons -> OK?
 */
export const lessonsControllerOkV1 = <ThrowOnError extends boolean = false>(options?: Options<LessonsControllerOkV1Data, ThrowOnError>) => {
    return (options?.client ?? client).get<LessonsControllerOkV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/lessons/ok',
        ...options
    });
};

/**
 * Get all steps (w/ lessons)
 */
export const curriculumStepsControllerFindAllWithLessonsV1 = <ThrowOnError extends boolean = false>(options?: Options<CurriculumStepsControllerFindAllWithLessonsV1Data, ThrowOnError>) => {
    return (options?.client ?? client).get<CurriculumStepsControllerFindAllWithLessonsV1Responses, unknown, ThrowOnError>({
        url: '/api/v1/curriculum-steps',
        ...options
    });
};
