// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type CreateCourseReqDto = {
    title: string;
    description: string | null;
};

export type CourseResDto = {
    id: number;
    title: string;
    description: string | null;
};

export type LessonResDto = {
    id: number;
    title: string;
};

export type CourseWithLessonsResDto = {
    id: number;
    title: string;
    description: string | null;
    lessons: Array<LessonResDto>;
};

export type UpdateCourseReqDto = {
    title?: string;
    description?: string | null;
};

export type DeletedResDto = {
    id: number;
};

export type CreateLessonReqDto = {
    title: string;
};

export type OkResDto = {
    ok: boolean;
};

export type PieceResDto = {
    id: number;
    position: number;
    type: 'Text' | 'Video' | 'Audio' | 'Separator' | 'Image';
    payload: string | null;
};

export type LessonWithPiecesResDto = {
    id: number;
    title: string;
    pieces: Array<PieceResDto>;
};

export type UpdateLessonReqDto = {
    title?: string;
};

export type PieceWithStatusResDto = {
    id: number;
    position: number;
    type: 'Text' | 'Video' | 'Audio' | 'Separator' | 'Image';
    payload: string | null;
    status: 'Untouched' | 'Edited' | 'Created' | 'Deleted';
};

export type LessonContentResDto = {
    content: Array<PieceWithStatusResDto>;
};

export type CurriculumStepWithLessonResDto = {
    lesson: LessonResDto;
    id: number;
    position: number;
};

export type CoursesControllerFindAllV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/courses';
};

export type CoursesControllerFindAllV1Responses = {
    200: Array<CourseResDto>;
};

export type CoursesControllerFindAllV1Response = CoursesControllerFindAllV1Responses[keyof CoursesControllerFindAllV1Responses];

export type CoursesControllerCreateOneV1Data = {
    body: CreateCourseReqDto;
    path?: never;
    query?: never;
    url: '/api/v1/courses';
};

export type CoursesControllerCreateOneV1Responses = {
    201: CourseResDto;
};

export type CoursesControllerCreateOneV1Response = CoursesControllerCreateOneV1Responses[keyof CoursesControllerCreateOneV1Responses];

export type CoursesControllerRemoveOneByIdV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type CoursesControllerRemoveOneByIdV1Responses = {
    200: DeletedResDto;
};

export type CoursesControllerRemoveOneByIdV1Response = CoursesControllerRemoveOneByIdV1Responses[keyof CoursesControllerRemoveOneByIdV1Responses];

export type CoursesControllerFindOneByIdWithLessonsV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type CoursesControllerFindOneByIdWithLessonsV1Responses = {
    200: CourseWithLessonsResDto;
};

export type CoursesControllerFindOneByIdWithLessonsV1Response = CoursesControllerFindOneByIdWithLessonsV1Responses[keyof CoursesControllerFindOneByIdWithLessonsV1Responses];

export type CoursesControllerUpdateOneByIdV1Data = {
    body: UpdateCourseReqDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type CoursesControllerUpdateOneByIdV1Responses = {
    200: CourseResDto;
};

export type CoursesControllerUpdateOneByIdV1Response = CoursesControllerUpdateOneByIdV1Responses[keyof CoursesControllerUpdateOneByIdV1Responses];

export type CoursesControllerCreateOneLessonByCourseIdV1Data = {
    body: CreateLessonReqDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/courses/{id}/lesson';
};

export type CoursesControllerCreateOneLessonByCourseIdV1Responses = {
    201: LessonResDto;
};

export type CoursesControllerCreateOneLessonByCourseIdV1Response = CoursesControllerCreateOneLessonByCourseIdV1Responses[keyof CoursesControllerCreateOneLessonByCourseIdV1Responses];

export type LessonsControllerOkV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/lessons/ok';
};

export type LessonsControllerOkV1Responses = {
    200: OkResDto;
};

export type LessonsControllerOkV1Response = LessonsControllerOkV1Responses[keyof LessonsControllerOkV1Responses];

export type LessonsControllerRemoveOneByIdV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/lessons/{id}';
};

export type LessonsControllerRemoveOneByIdV1Responses = {
    200: DeletedResDto;
};

export type LessonsControllerRemoveOneByIdV1Response = LessonsControllerRemoveOneByIdV1Responses[keyof LessonsControllerRemoveOneByIdV1Responses];

export type LessonsControllerFindOneByIdWithPiecesV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/lessons/{id}';
};

export type LessonsControllerFindOneByIdWithPiecesV1Responses = {
    200: LessonWithPiecesResDto;
};

export type LessonsControllerFindOneByIdWithPiecesV1Response = LessonsControllerFindOneByIdWithPiecesV1Responses[keyof LessonsControllerFindOneByIdWithPiecesV1Responses];

export type LessonsControllerUpdateOneByIdV1Data = {
    body: UpdateLessonReqDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/lessons/{id}';
};

export type LessonsControllerUpdateOneByIdV1Responses = {
    200: LessonResDto;
};

export type LessonsControllerUpdateOneByIdV1Response = LessonsControllerUpdateOneByIdV1Responses[keyof LessonsControllerUpdateOneByIdV1Responses];

export type LessonsControllerGetContentOfOneByIdV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/lessons/{id}/content';
};

export type LessonsControllerGetContentOfOneByIdV1Responses = {
    200: LessonContentResDto;
};

export type LessonsControllerGetContentOfOneByIdV1Response = LessonsControllerGetContentOfOneByIdV1Responses[keyof LessonsControllerGetContentOfOneByIdV1Responses];

export type CurriculumStepsControllerFindAllWithLessonsV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/curriculum-steps';
};

export type CurriculumStepsControllerFindAllWithLessonsV1Responses = {
    200: Array<CurriculumStepWithLessonResDto>;
};

export type CurriculumStepsControllerFindAllWithLessonsV1Response = CurriculumStepsControllerFindAllWithLessonsV1Responses[keyof CurriculumStepsControllerFindAllWithLessonsV1Responses];
