// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3002/api' | (string & {});
};

export type FolderOnlyResponseDto = {
    id: number;
    title: string;
    description: string | null;
    type: 'PATH' | 'COURSE';
    position: number;
};

export type PieceResponseDto = {
    id: number;
    position: number;
    type: 'VIDEO' | 'AUDIO' | 'TEXT';
    payload: {
        [key: string]: unknown;
    };
    folderId: number;
};

export type FolderWithRelationsResponseDto = {
    subFolders: Array<FolderOnlyResponseDto>;
    pieces: Array<PieceResponseDto>;
    id: number;
    title: string;
    description: string | null;
    type: 'PATH' | 'COURSE';
    position: number;
};

export type CreateFolderDto = {
    title: string;
    description?: string;
    type?: 'PATH' | 'COURSE';
    position?: number;
    parentFolderIds?: Array<number>;
};

export type CreatePieceDto = {
    position?: number;
    type: 'VIDEO' | 'AUDIO' | 'TEXT';
    payload: {
        [key: string]: unknown;
    };
    folderId: number;
};

export type FoldersControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/folders';
};

export type FoldersControllerGetAllResponses = {
    200: Array<FolderWithRelationsResponseDto>;
};

export type FoldersControllerGetAllResponse = FoldersControllerGetAllResponses[keyof FoldersControllerGetAllResponses];

export type FoldersControllerCreateData = {
    body: CreateFolderDto;
    path?: never;
    query?: never;
    url: '/folders';
};

export type FoldersControllerCreateResponses = {
    201: FolderWithRelationsResponseDto;
};

export type FoldersControllerCreateResponse = FoldersControllerCreateResponses[keyof FoldersControllerCreateResponses];

export type FoldersControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/folders/{id}';
};

export type FoldersControllerRemoveResponses = {
    204: void;
};

export type FoldersControllerRemoveResponse = FoldersControllerRemoveResponses[keyof FoldersControllerRemoveResponses];

export type FoldersControllerGetByIdData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/folders/{id}';
};

export type FoldersControllerGetByIdResponses = {
    200: FolderWithRelationsResponseDto;
};

export type FoldersControllerGetByIdResponse = FoldersControllerGetByIdResponses[keyof FoldersControllerGetByIdResponses];

export type PiecesControllerGetAllData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/pieces';
};

export type PiecesControllerGetAllResponses = {
    200: Array<PieceResponseDto>;
};

export type PiecesControllerGetAllResponse = PiecesControllerGetAllResponses[keyof PiecesControllerGetAllResponses];

export type PiecesControllerCreateData = {
    body: CreatePieceDto;
    path?: never;
    query?: never;
    url: '/pieces';
};

export type PiecesControllerCreateResponses = {
    201: PieceResponseDto;
};

export type PiecesControllerCreateResponse = PiecesControllerCreateResponses[keyof PiecesControllerCreateResponses];

export type PiecesControllerRemoveData = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/pieces/{id}';
};

export type PiecesControllerRemoveResponses = {
    204: void;
};

export type PiecesControllerRemoveResponse = PiecesControllerRemoveResponses[keyof PiecesControllerRemoveResponses];

export type SeedControllerSeedData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/seed';
};

export type SeedControllerSeedResponses = {
    204: void;
};

export type SeedControllerSeedResponse = SeedControllerSeedResponses[keyof SeedControllerSeedResponses];
