// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001' | (string & {});
};

export type CreateCourseReqDto = {
    title: string;
    description: string | null;
};

export type CourseResDto = {
    id: number;
    title: string;
    description: string | null;
};

export type UpdateCourseReqDto = {
    title?: string;
    description?: string | null;
};

export type DeletedResDto = {
    id: number;
};

export type LessonResDto = {
    id: number;
    title: string;
};

export type CurriculumStepWithLessonResDto = {
    lesson: LessonResDto;
    id: number;
    position: number;
};

export type OkResDto = {
    ok: boolean;
};

export type CoursesControllerFindAllV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/courses';
};

export type CoursesControllerFindAllV1Responses = {
    200: Array<CourseResDto>;
};

export type CoursesControllerFindAllV1Response = CoursesControllerFindAllV1Responses[keyof CoursesControllerFindAllV1Responses];

export type CoursesControllerCreateOneV1Data = {
    body: CreateCourseReqDto;
    path?: never;
    query?: never;
    url: '/api/v1/courses';
};

export type CoursesControllerCreateOneV1Responses = {
    201: CourseResDto;
};

export type CoursesControllerCreateOneV1Response = CoursesControllerCreateOneV1Responses[keyof CoursesControllerCreateOneV1Responses];

export type CoursesControllerRemoveOneByIdV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type CoursesControllerRemoveOneByIdV1Responses = {
    200: DeletedResDto;
};

export type CoursesControllerRemoveOneByIdV1Response = CoursesControllerRemoveOneByIdV1Responses[keyof CoursesControllerRemoveOneByIdV1Responses];

export type CoursesControllerFindOneByIdV1Data = {
    body?: never;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type CoursesControllerFindOneByIdV1Responses = {
    200: CourseResDto;
};

export type CoursesControllerFindOneByIdV1Response = CoursesControllerFindOneByIdV1Responses[keyof CoursesControllerFindOneByIdV1Responses];

export type CoursesControllerUpdateOneByIdV1Data = {
    body: UpdateCourseReqDto;
    path: {
        id: number;
    };
    query?: never;
    url: '/api/v1/courses/{id}';
};

export type CoursesControllerUpdateOneByIdV1Responses = {
    200: CourseResDto;
};

export type CoursesControllerUpdateOneByIdV1Response = CoursesControllerUpdateOneByIdV1Responses[keyof CoursesControllerUpdateOneByIdV1Responses];

export type CurriculumStepsControllerFindAllWithLessonsV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/curriculum-steps';
};

export type CurriculumStepsControllerFindAllWithLessonsV1Responses = {
    200: Array<CurriculumStepWithLessonResDto>;
};

export type CurriculumStepsControllerFindAllWithLessonsV1Response = CurriculumStepsControllerFindAllWithLessonsV1Responses[keyof CurriculumStepsControllerFindAllWithLessonsV1Responses];

export type LessonsControllerOkV1Data = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/lessons/ok';
};

export type LessonsControllerOkV1Responses = {
    200: OkResDto;
};

export type LessonsControllerOkV1Response = LessonsControllerOkV1Responses[keyof LessonsControllerOkV1Responses];
