/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AdminAuthRouteImport } from './routes/admin/auth'
import { Route as AppFoldersIndexRouteImport } from './routes/_app/folders/index'
import { Route as AppFoldersIdRouteImport } from './routes/_app/folders/$id'

const AppIndexRoute = AppIndexRouteImport.update({
  id: '/_app/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuthRoute = AdminAuthRouteImport.update({
  id: '/admin/auth',
  path: '/admin/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFoldersIndexRoute = AppFoldersIndexRouteImport.update({
  id: '/_app/folders/',
  path: '/folders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFoldersIdRoute = AppFoldersIdRouteImport.update({
  id: '/_app/folders/$id',
  path: '/folders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/admin/auth': typeof AdminAuthRoute
  '/': typeof AppIndexRoute
  '/folders/$id': typeof AppFoldersIdRoute
  '/folders': typeof AppFoldersIndexRoute
}
export interface FileRoutesByTo {
  '/admin/auth': typeof AdminAuthRoute
  '/': typeof AppIndexRoute
  '/folders/$id': typeof AppFoldersIdRoute
  '/folders': typeof AppFoldersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/admin/auth': typeof AdminAuthRoute
  '/_app/': typeof AppIndexRoute
  '/_app/folders/$id': typeof AppFoldersIdRoute
  '/_app/folders/': typeof AppFoldersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/admin/auth' | '/' | '/folders/$id' | '/folders'
  fileRoutesByTo: FileRoutesByTo
  to: '/admin/auth' | '/' | '/folders/$id' | '/folders'
  id:
    | '__root__'
    | '/admin/auth'
    | '/_app/'
    | '/_app/folders/$id'
    | '/_app/folders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminAuthRoute: typeof AdminAuthRoute
  AppIndexRoute: typeof AppIndexRoute
  AppFoldersIdRoute: typeof AppFoldersIdRoute
  AppFoldersIndexRoute: typeof AppFoldersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/auth': {
      id: '/admin/auth'
      path: '/admin/auth'
      fullPath: '/admin/auth'
      preLoaderRoute: typeof AdminAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/folders/': {
      id: '/_app/folders/'
      path: '/folders'
      fullPath: '/folders'
      preLoaderRoute: typeof AppFoldersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/folders/$id': {
      id: '/_app/folders/$id'
      path: '/folders/$id'
      fullPath: '/folders/$id'
      preLoaderRoute: typeof AppFoldersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  AdminAuthRoute: AdminAuthRoute,
  AppIndexRoute: AppIndexRoute,
  AppFoldersIdRoute: AppFoldersIdRoute,
  AppFoldersIndexRoute: AppFoldersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
