/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as AdminIndexRouteImport } from "./routes/admin/index"
import { Route as AppIndexRouteImport } from "./routes/_app/index"
import { Route as AppCurriculumIndexRouteImport } from "./routes/_app/curriculum/index"
import { Route as AppCoursesIndexRouteImport } from "./routes/_app/courses/index"
import { Route as AppCoursesNewRouteImport } from "./routes/_app/courses/new"
import { Route as AppCoursesIdRouteRouteImport } from "./routes/_app/courses/$id/route"
import { Route as AppCoursesIdViewRouteImport } from "./routes/_app/courses/$id/view"
import { Route as AppCoursesIdEditRouteImport } from "./routes/_app/courses/$id/edit"

const AdminIndexRoute = AdminIndexRouteImport.update({
  id: "/admin/",
  path: "/admin/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: "/_app/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCurriculumIndexRoute = AppCurriculumIndexRouteImport.update({
  id: "/_app/curriculum/",
  path: "/curriculum/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIndexRoute = AppCoursesIndexRouteImport.update({
  id: "/_app/courses/",
  path: "/courses/",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesNewRoute = AppCoursesNewRouteImport.update({
  id: "/_app/courses/new",
  path: "/courses/new",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIdRouteRoute = AppCoursesIdRouteRouteImport.update({
  id: "/_app/courses/$id",
  path: "/courses/$id",
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoursesIdViewRoute = AppCoursesIdViewRouteImport.update({
  id: "/view",
  path: "/view",
  getParentRoute: () => AppCoursesIdRouteRoute,
} as any)
const AppCoursesIdEditRoute = AppCoursesIdEditRouteImport.update({
  id: "/edit",
  path: "/edit",
  getParentRoute: () => AppCoursesIdRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  "/": typeof AppIndexRoute
  "/admin": typeof AdminIndexRoute
  "/courses/$id": typeof AppCoursesIdRouteRouteWithChildren
  "/courses/new": typeof AppCoursesNewRoute
  "/courses": typeof AppCoursesIndexRoute
  "/curriculum": typeof AppCurriculumIndexRoute
  "/courses/$id/edit": typeof AppCoursesIdEditRoute
  "/courses/$id/view": typeof AppCoursesIdViewRoute
}
export interface FileRoutesByTo {
  "/": typeof AppIndexRoute
  "/admin": typeof AdminIndexRoute
  "/courses/$id": typeof AppCoursesIdRouteRouteWithChildren
  "/courses/new": typeof AppCoursesNewRoute
  "/courses": typeof AppCoursesIndexRoute
  "/curriculum": typeof AppCurriculumIndexRoute
  "/courses/$id/edit": typeof AppCoursesIdEditRoute
  "/courses/$id/view": typeof AppCoursesIdViewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/_app/": typeof AppIndexRoute
  "/admin/": typeof AdminIndexRoute
  "/_app/courses/$id": typeof AppCoursesIdRouteRouteWithChildren
  "/_app/courses/new": typeof AppCoursesNewRoute
  "/_app/courses/": typeof AppCoursesIndexRoute
  "/_app/curriculum/": typeof AppCurriculumIndexRoute
  "/_app/courses/$id/edit": typeof AppCoursesIdEditRoute
  "/_app/courses/$id/view": typeof AppCoursesIdViewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/admin"
    | "/courses/$id"
    | "/courses/new"
    | "/courses"
    | "/curriculum"
    | "/courses/$id/edit"
    | "/courses/$id/view"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/admin"
    | "/courses/$id"
    | "/courses/new"
    | "/courses"
    | "/curriculum"
    | "/courses/$id/edit"
    | "/courses/$id/view"
  id:
    | "__root__"
    | "/_app/"
    | "/admin/"
    | "/_app/courses/$id"
    | "/_app/courses/new"
    | "/_app/courses/"
    | "/_app/curriculum/"
    | "/_app/courses/$id/edit"
    | "/_app/courses/$id/view"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppCoursesIdRouteRoute: typeof AppCoursesIdRouteRouteWithChildren
  AppCoursesNewRoute: typeof AppCoursesNewRoute
  AppCoursesIndexRoute: typeof AppCoursesIndexRoute
  AppCurriculumIndexRoute: typeof AppCurriculumIndexRoute
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/admin/": {
      id: "/admin/"
      path: "/admin"
      fullPath: "/admin"
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/": {
      id: "/_app/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/curriculum/": {
      id: "/_app/curriculum/"
      path: "/curriculum"
      fullPath: "/curriculum"
      preLoaderRoute: typeof AppCurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/": {
      id: "/_app/courses/"
      path: "/courses"
      fullPath: "/courses"
      preLoaderRoute: typeof AppCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/new": {
      id: "/_app/courses/new"
      path: "/courses/new"
      fullPath: "/courses/new"
      preLoaderRoute: typeof AppCoursesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$id": {
      id: "/_app/courses/$id"
      path: "/courses/$id"
      fullPath: "/courses/$id"
      preLoaderRoute: typeof AppCoursesIdRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/_app/courses/$id/view": {
      id: "/_app/courses/$id/view"
      path: "/view"
      fullPath: "/courses/$id/view"
      preLoaderRoute: typeof AppCoursesIdViewRouteImport
      parentRoute: typeof AppCoursesIdRouteRoute
    }
    "/_app/courses/$id/edit": {
      id: "/_app/courses/$id/edit"
      path: "/edit"
      fullPath: "/courses/$id/edit"
      preLoaderRoute: typeof AppCoursesIdEditRouteImport
      parentRoute: typeof AppCoursesIdRouteRoute
    }
  }
}

interface AppCoursesIdRouteRouteChildren {
  AppCoursesIdEditRoute: typeof AppCoursesIdEditRoute
  AppCoursesIdViewRoute: typeof AppCoursesIdViewRoute
}

const AppCoursesIdRouteRouteChildren: AppCoursesIdRouteRouteChildren = {
  AppCoursesIdEditRoute: AppCoursesIdEditRoute,
  AppCoursesIdViewRoute: AppCoursesIdViewRoute,
}

const AppCoursesIdRouteRouteWithChildren =
  AppCoursesIdRouteRoute._addFileChildren(AppCoursesIdRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppCoursesIdRouteRoute: AppCoursesIdRouteRouteWithChildren,
  AppCoursesNewRoute: AppCoursesNewRoute,
  AppCoursesIndexRoute: AppCoursesIndexRoute,
  AppCurriculumIndexRoute: AppCurriculumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
