// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { foldersControllerCreate, foldersControllerGetAll, foldersControllerGetById, foldersControllerRemove, type Options, piecesControllerCreate, piecesControllerGetAll, piecesControllerRemove, seedControllerSeed } from '../sdk.gen';
import type { FoldersControllerCreateData, FoldersControllerCreateResponse, FoldersControllerGetAllData, FoldersControllerGetByIdData, FoldersControllerRemoveData, FoldersControllerRemoveResponse, PiecesControllerCreateData, PiecesControllerCreateResponse, PiecesControllerGetAllData, PiecesControllerRemoveData, PiecesControllerRemoveResponse, SeedControllerSeedData, SeedControllerSeedResponse } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const foldersControllerGetAllQueryKey = (options?: Options<FoldersControllerGetAllData>) => createQueryKey('foldersControllerGetAll', options);

/**
 * Get all (parent) folders
 */
export const foldersControllerGetAllOptions = (options?: Options<FoldersControllerGetAllData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await foldersControllerGetAll({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: foldersControllerGetAllQueryKey(options)
    });
};

/**
 * Create a folder
 */
export const foldersControllerCreateMutation = (options?: Partial<Options<FoldersControllerCreateData>>): UseMutationOptions<FoldersControllerCreateResponse, DefaultError, Options<FoldersControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<FoldersControllerCreateResponse, DefaultError, Options<FoldersControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await foldersControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a folder
 */
export const foldersControllerRemoveMutation = (options?: Partial<Options<FoldersControllerRemoveData>>): UseMutationOptions<FoldersControllerRemoveResponse, DefaultError, Options<FoldersControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<FoldersControllerRemoveResponse, DefaultError, Options<FoldersControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await foldersControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const foldersControllerGetByIdQueryKey = (options: Options<FoldersControllerGetByIdData>) => createQueryKey('foldersControllerGetById', options);

/**
 * Get folder by ID
 */
export const foldersControllerGetByIdOptions = (options: Options<FoldersControllerGetByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await foldersControllerGetById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: foldersControllerGetByIdQueryKey(options)
    });
};

export const piecesControllerGetAllQueryKey = (options?: Options<PiecesControllerGetAllData>) => createQueryKey('piecesControllerGetAll', options);

/**
 * Get all pieces
 */
export const piecesControllerGetAllOptions = (options?: Options<PiecesControllerGetAllData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await piecesControllerGetAll({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: piecesControllerGetAllQueryKey(options)
    });
};

/**
 * Create a piece
 */
export const piecesControllerCreateMutation = (options?: Partial<Options<PiecesControllerCreateData>>): UseMutationOptions<PiecesControllerCreateResponse, DefaultError, Options<PiecesControllerCreateData>> => {
    const mutationOptions: UseMutationOptions<PiecesControllerCreateResponse, DefaultError, Options<PiecesControllerCreateData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await piecesControllerCreate({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a piece
 */
export const piecesControllerRemoveMutation = (options?: Partial<Options<PiecesControllerRemoveData>>): UseMutationOptions<PiecesControllerRemoveResponse, DefaultError, Options<PiecesControllerRemoveData>> => {
    const mutationOptions: UseMutationOptions<PiecesControllerRemoveResponse, DefaultError, Options<PiecesControllerRemoveData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await piecesControllerRemove({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Seed the DB.
 */
export const seedControllerSeedMutation = (options?: Partial<Options<SeedControllerSeedData>>): UseMutationOptions<SeedControllerSeedResponse, DefaultError, Options<SeedControllerSeedData>> => {
    const mutationOptions: UseMutationOptions<SeedControllerSeedResponse, DefaultError, Options<SeedControllerSeedData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await seedControllerSeed({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
