// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { coursesControllerCreateOneLessonByCourseIdV1, coursesControllerCreateOneV1, coursesControllerFindAllV1, coursesControllerFindOneByIdWithLessonsV1, coursesControllerRemoveOneByIdV1, coursesControllerUpdateOneByIdV1, curriculumStepsControllerFindAllWithLessonsV1, lessonsControllerFindOneByIdWithPiecesV1, lessonsControllerGetContentOfOneByIdV1, lessonsControllerOkV1, lessonsControllerRemoveOneByIdV1, lessonsControllerUpdateOneByIdV1, type Options } from '../sdk.gen';
import type { CoursesControllerCreateOneLessonByCourseIdV1Data, CoursesControllerCreateOneLessonByCourseIdV1Response, CoursesControllerCreateOneV1Data, CoursesControllerCreateOneV1Response, CoursesControllerFindAllV1Data, CoursesControllerFindOneByIdWithLessonsV1Data, CoursesControllerRemoveOneByIdV1Data, CoursesControllerRemoveOneByIdV1Response, CoursesControllerUpdateOneByIdV1Data, CoursesControllerUpdateOneByIdV1Response, CurriculumStepsControllerFindAllWithLessonsV1Data, LessonsControllerFindOneByIdWithPiecesV1Data, LessonsControllerGetContentOfOneByIdV1Data, LessonsControllerOkV1Data, LessonsControllerRemoveOneByIdV1Data, LessonsControllerRemoveOneByIdV1Response, LessonsControllerUpdateOneByIdV1Data, LessonsControllerUpdateOneByIdV1Response } from '../types.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const coursesControllerFindAllV1QueryKey = (options?: Options<CoursesControllerFindAllV1Data>) => createQueryKey('coursesControllerFindAllV1', options);

/**
 * Get courses
 */
export const coursesControllerFindAllV1Options = (options?: Options<CoursesControllerFindAllV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await coursesControllerFindAllV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: coursesControllerFindAllV1QueryKey(options)
    });
};

/**
 * Create a course
 */
export const coursesControllerCreateOneV1Mutation = (options?: Partial<Options<CoursesControllerCreateOneV1Data>>): UseMutationOptions<CoursesControllerCreateOneV1Response, DefaultError, Options<CoursesControllerCreateOneV1Data>> => {
    const mutationOptions: UseMutationOptions<CoursesControllerCreateOneV1Response, DefaultError, Options<CoursesControllerCreateOneV1Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await coursesControllerCreateOneV1({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete a course
 */
export const coursesControllerRemoveOneByIdV1Mutation = (options?: Partial<Options<CoursesControllerRemoveOneByIdV1Data>>): UseMutationOptions<CoursesControllerRemoveOneByIdV1Response, DefaultError, Options<CoursesControllerRemoveOneByIdV1Data>> => {
    const mutationOptions: UseMutationOptions<CoursesControllerRemoveOneByIdV1Response, DefaultError, Options<CoursesControllerRemoveOneByIdV1Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await coursesControllerRemoveOneByIdV1({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const coursesControllerFindOneByIdWithLessonsV1QueryKey = (options: Options<CoursesControllerFindOneByIdWithLessonsV1Data>) => createQueryKey('coursesControllerFindOneByIdWithLessonsV1', options);

/**
 * Get a course (w/ lessons)
 */
export const coursesControllerFindOneByIdWithLessonsV1Options = (options: Options<CoursesControllerFindOneByIdWithLessonsV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await coursesControllerFindOneByIdWithLessonsV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: coursesControllerFindOneByIdWithLessonsV1QueryKey(options)
    });
};

/**
 * Update a course
 */
export const coursesControllerUpdateOneByIdV1Mutation = (options?: Partial<Options<CoursesControllerUpdateOneByIdV1Data>>): UseMutationOptions<CoursesControllerUpdateOneByIdV1Response, DefaultError, Options<CoursesControllerUpdateOneByIdV1Data>> => {
    const mutationOptions: UseMutationOptions<CoursesControllerUpdateOneByIdV1Response, DefaultError, Options<CoursesControllerUpdateOneByIdV1Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await coursesControllerUpdateOneByIdV1({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Create lesson by course ID
 */
export const coursesControllerCreateOneLessonByCourseIdV1Mutation = (options?: Partial<Options<CoursesControllerCreateOneLessonByCourseIdV1Data>>): UseMutationOptions<CoursesControllerCreateOneLessonByCourseIdV1Response, DefaultError, Options<CoursesControllerCreateOneLessonByCourseIdV1Data>> => {
    const mutationOptions: UseMutationOptions<CoursesControllerCreateOneLessonByCourseIdV1Response, DefaultError, Options<CoursesControllerCreateOneLessonByCourseIdV1Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await coursesControllerCreateOneLessonByCourseIdV1({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonsControllerOkV1QueryKey = (options?: Options<LessonsControllerOkV1Data>) => createQueryKey('lessonsControllerOkV1', options);

/**
 * Lessons -> OK?
 */
export const lessonsControllerOkV1Options = (options?: Options<LessonsControllerOkV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await lessonsControllerOkV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: lessonsControllerOkV1QueryKey(options)
    });
};

/**
 * Delete a lesson
 */
export const lessonsControllerRemoveOneByIdV1Mutation = (options?: Partial<Options<LessonsControllerRemoveOneByIdV1Data>>): UseMutationOptions<LessonsControllerRemoveOneByIdV1Response, DefaultError, Options<LessonsControllerRemoveOneByIdV1Data>> => {
    const mutationOptions: UseMutationOptions<LessonsControllerRemoveOneByIdV1Response, DefaultError, Options<LessonsControllerRemoveOneByIdV1Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lessonsControllerRemoveOneByIdV1({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonsControllerFindOneByIdWithPiecesV1QueryKey = (options: Options<LessonsControllerFindOneByIdWithPiecesV1Data>) => createQueryKey('lessonsControllerFindOneByIdWithPiecesV1', options);

/**
 * Get a lesson (w/ pieces)
 */
export const lessonsControllerFindOneByIdWithPiecesV1Options = (options: Options<LessonsControllerFindOneByIdWithPiecesV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await lessonsControllerFindOneByIdWithPiecesV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: lessonsControllerFindOneByIdWithPiecesV1QueryKey(options)
    });
};

/**
 * Update a lesson
 */
export const lessonsControllerUpdateOneByIdV1Mutation = (options?: Partial<Options<LessonsControllerUpdateOneByIdV1Data>>): UseMutationOptions<LessonsControllerUpdateOneByIdV1Response, DefaultError, Options<LessonsControllerUpdateOneByIdV1Data>> => {
    const mutationOptions: UseMutationOptions<LessonsControllerUpdateOneByIdV1Response, DefaultError, Options<LessonsControllerUpdateOneByIdV1Data>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await lessonsControllerUpdateOneByIdV1({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const lessonsControllerGetContentOfOneByIdV1QueryKey = (options: Options<LessonsControllerGetContentOfOneByIdV1Data>) => createQueryKey('lessonsControllerGetContentOfOneByIdV1', options);

/**
 * Get a lesson's content
 */
export const lessonsControllerGetContentOfOneByIdV1Options = (options: Options<LessonsControllerGetContentOfOneByIdV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await lessonsControllerGetContentOfOneByIdV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: lessonsControllerGetContentOfOneByIdV1QueryKey(options)
    });
};

export const curriculumStepsControllerFindAllWithLessonsV1QueryKey = (options?: Options<CurriculumStepsControllerFindAllWithLessonsV1Data>) => createQueryKey('curriculumStepsControllerFindAllWithLessonsV1', options);

/**
 * Get all steps (w/ lessons)
 */
export const curriculumStepsControllerFindAllWithLessonsV1Options = (options?: Options<CurriculumStepsControllerFindAllWithLessonsV1Data>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await curriculumStepsControllerFindAllWithLessonsV1({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: curriculumStepsControllerFindAllWithLessonsV1QueryKey(options)
    });
};
